repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: "mkdocs.*\\.yml$"  # Exclude mkdocs YAML files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5  # Use whatever version you're currently using
    hooks:
      - id: ruff
        args: [--fix]
        exclude: "hooks/.*\\.py$"  # Exclude the hooks directory from ruff
      - id: ruff-format
