name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install uv + Python
        uses: astral-sh/setup-uv@v6.7.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run Ruff check
        run: uv run ruff check . --config pyproject.toml --output-format=github

      - name: Run Ruff format check
        run: uv run ruff format . --config pyproject.toml --check
